Final Version of the Smashing Magazine Design Teardown
Eshy10/The-Next-Web-Clone pull request #2
Opened 2020-02-05 15:36 UTC by Spayco

## Building with Responsive Design: The Next Web Clone
- Added NavBar
- Added Main Section
- Added Footer
- Responsive to 2 extra sizes
- No Linter Issues

[Live Demo](https://raw.githack.com/Eshy10/The-Next-Web-Clone/feature-page/index.html)

2020-02-05 16:01 UTC, nikasulo requested changes
# Really fantastic job @Spayco and @Eshy10 
It is all coming together and shining! Please consider my comments below, make the required changes and request another review :handshake: 

#### Horizontal Scroll
You seem to have a little bug with one of the elements of the page, shooting out beyond the browser's maximum width. This may be as a result of a margin or padding you have set up. One of the easiest ways I have found to correct this issue is to set the default `box-sizing` property to `border-box` as follows `*{box-sizing: border-box}`. Please read some more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing).

#### Responsiveness
Your project could use a little more responsiveness, please look a little more closely at the sizes of elements, padding of sections, margins, and general element positionings. These are very key as they will affect the look, feel, and more importantly the usability of your sites. I went ahead to attach a few images of areas where I noticed issues with responsiveness, however, please do a full scan of your page just in case I missed or left something out.
![screenshot](https://images2.imgbox.com/05/5c/RDsJSsNJ_o.png)
![screenshot](https://images2.imgbox.com/f0/68/8he0ETzK_o.png)
![screenshot](https://images2.imgbox.com/89/74/T4pYoFvk_o.png)

### Summary
You have come a long way and your hard work is glaring. Please consider my comments below, so your project can shine even more than it already does! Look out for any element that is causing the horizontal scroll, and look into your mobile responsiveness thoroughly, and you should be good to go. I wish you all the best in this and all other projects. See you at the top! :rocket:

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-06 11:23 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

## Hello @Eshy10 and @Spayco :balloon: :lollipop: 

### Amazing job so far :medal_sports: your project is looking more similar to the original :art:  every time and has good use of semantic HTML and the Readme file is stellar :star: Still, there are a few changes to work on before we can give you the approval:

## Small Screens

**navbar**

- [x] All links in the navbar are hidden and the TWN logo has to appear in the leftmost part of it

- [x] it's missing a hamburger icon in the rightmost part of the navbar

- Yours

![image](https://user-images.githubusercontent.com/52209067/73929753-050b9f80-489b-11ea-9c42-e77c9f13b4b4.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/73929805-181e6f80-489b-11ea-8998-71fd77e2a385.png)

**Latest Fundings**

- [x] the last article in this section should be hidden (the original only has 3, you have 4)

**Footer**

- [x] The text in the footer should be centered and place in 3 rows just like the original

- Yours

![image](https://user-images.githubusercontent.com/52209067/73930467-27ea8380-489c-11ea-8643-044a8e58af65.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/73930498-35a00900-489c-11ea-900c-e877060cf8d7.png)

## Medium Screens (width > 768px)

**navbar**

- [x] most of the links in the navbar are showing and the TWN logo has to appear in the leftmost part of it

- Yours

![image](https://user-images.githubusercontent.com/52209067/73930879-ef977500-489c-11ea-979a-74358b4a4711.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/73930913-fe7e2780-489c-11ea-8715-8516ea2df346.png)

**Main Articles**

- [x] it has one article in the leftmost part of the page and 2 in the rightmost one

- Yours

![image](https://user-images.githubusercontent.com/52209067/73931098-5583fc80-489d-11ea-971b-f89e01769ec7.png)


- Original

![image](https://user-images.githubusercontent.com/52209067/73931130-60d72800-489d-11ea-9992-1e576e170f75.png)

**Latest news**

- [x] this section has 3 articles per row in this screen size

- Yours

![image](https://user-images.githubusercontent.com/52209067/73931250-9845d480-489d-11ea-825c-83b0e83ae1a6.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/73931295-a8f64a80-489d-11ea-950b-526f4babef79.png)

**Latest Fundings**

- [x] Only one row with 3 articles in it

- Yours

![image](https://user-images.githubusercontent.com/52209067/73931417-e2c75100-489d-11ea-9a69-70b0b6e826a6.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/73931450-f2469a00-489d-11ea-8f7a-8f79413d2100.png)

**Categories (Apps, GERA, Tech, etc) section**

- [x] must have 2 articles per row

- Yours

![image](https://user-images.githubusercontent.com/52209067/73931601-346fdb80-489e-11ea-8ed3-c77554708ed1.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/73931658-45b8e800-489e-11ea-99cf-519bb6f69528.png)

**Latest Deals**

- [x] has 3 articles per row

- Yours

![image](https://user-images.githubusercontent.com/52209067/73931758-7567f000-489e-11ea-90d7-02fc545f9a85.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/73931789-83b60c00-489e-11ea-968c-a73b152302b9.png)

## Large Screens (width > 1023px)

**All sections**

- [x] articles should have more space in between them so they take at least 95% of the page width

- Yours

![image](https://user-images.githubusercontent.com/52209067/73932455-ff648880-489f-11ea-8f4d-11db01d3d362.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/73932489-0f7c6800-48a0-11ea-964e-162e3efbfac3.png)

## CSS good practices

- [x] use or delete the unused fonts I have spotted in your code bellow  :arrow_down_small: 

### That's it team! :raised_hands: 

### Please :pray:  make the changes :memo:  and submit back for a code review when you are done :rocket: 

any questions? ask me in slack **@ Maru**

Happy Coding! :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-02-06 11:23 UTC, euqueme commented on fonts.css
> +@font-face { font-family: ARS Maquette; font-style: normal; font-weight: 700; src: url(https://cdn0.tnwcdn.com/wp-content/themes/cyberdelia/assets/fonts/ars-maquette-bold-alt.eot); src: url(https://c
delete these unused repeated fonts (lines #3 to #5)

2020-02-06 11:23 UTC, euqueme commented on fonts.css
> +@font-face { font-family: TNW-Avalon; font-style: normal; font-weight: 700; src: url(https://cdn0.tnwcdn.com/wp-content/themes/cyberdelia/assets/fonts/TNW-Avalon-Bold.otf); src: url(https://cdn0.tnwc
Delete this unused font (line #9)

2020-02-06 11:23 UTC, euqueme commented on fonts.css
> +@font-face { font-family: Graphik-Medium; font-style: normal; font-weight: 500; src: url(https://cdn4.tnwcdn.com/assets/fonts/graphik/graphik-medium.woff) format("woff"),url(https://cdn4.tnwcdn.com/a
Delete these unused fonts (line #13 to line #17)

2020-02-06 13:38 UTC, nikasulo requested changes
# Nice job team! @Spayco and @Eshy10 
You went on to fix the issues I pointed out during my last review, however, the issues @euqueme rightly pointed out on the tablet screen size(<=768px) still persist. In addition to those, there are some new issues with overflowing elements on the page.

#### Horizontal Scroll
You seem to have a little bug with one of the elements of the page, shooting out beyond the browser's maximum width. This may be as a result of a margin or padding you have set up. One of the easiest ways I have found to correct this issue is to set the default `box-sizing` property to `border-box` as follows `*{box-sizing: border-box}`. Please read some more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing). Please see attached screenshots
![screenshot](https://images2.imgbox.com/1b/23/x30s728F_o.png)
![screenshot](https://images2.imgbox.com/29/5e/LZL8e4Jz_o.png)
![screenshot](https://images2.imgbox.com/f8/68/BG9f58t3_o.png)

### Summary
You did a great job tackling the issues I pointed out in my last review. However, please take some time to consider my comments above in conjunction with what @euqueme rightly pointed out. This project is all about responsiveness and as such a lot of attention is paid to it in the reviews. Take some time and go through each section, examine it against the original page, make appropriate changes and request another review. I wish you the very best! See you at the top :medal_military: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-06 17:51 UTC, MauricioRobayo approved these changes
Congratulations, the project looks awesome and all the requirements are met!

Go ahead and merge 🚀.

Status: __Approve++__.

---

Please take note that some of your resources are not loading due to CORS policy. The fonts that you are requesting are being blocked by the browser, If you want to use them, you might want to host them yourselves... but make sure you have the rights to do so in that case. Also, check the font awesome that you're loading, it seems to be failing:

![image](https://user-images.githubusercontent.com/2121481/73963335-132edf80-48de-11ea-9506-c1addafd4cd1.png)

Please check these issues on the `Network` tab of the `Developer Tools` of the browser of your choice.

2020-02-06 17:51 UTC, MauricioRobayo commented on index.html
> +    <script src="https://kit.fontawesome.com/f02bbd63cf.js" crossorigin="anonymous"></script>
This file is not loading:

> GET https://kit.fontawesome.com/f02bbd63cf.js net::ERR_CONNECTION_CLOSED

Please make sure it is working fine before merging 💪.

2020-02-06 17:51 UTC, MauricioRobayo commented on fonts.css
> +@font-face { font-family: Shentox; font-style: normal; font-weight: 500; src: url(https://cdn0.tnwcdn.com/wp-content/themes/cyberdelia/assets/fonts/shentox-medium.eot); src: url(https://cdn0.tnwcdn.c
These resources are being blocked by the CORS policy on the browser:

> Access to font at 'https://cdn0.tnwcdn.com/wp-content/themes/cyberdelia/assets/fonts/shentox-medium.woff2' from origin 'https://raw.githack.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://thenextweb.com' that is not equal to the supplied origin.

2020-02-06 18:40 UTC, Spayco commented on fonts.css
> +@font-face { font-family: Shentox; font-style: normal; font-weight: 500; src: url(https://cdn0.tnwcdn.com/wp-content/themes/cyberdelia/assets/fonts/shentox-medium.eot); src: url(https://cdn0.tnwcdn.c
weird, for some reason, I don't get that error

2020-02-06 21:33 UTC, merged